### ISSUE TITLE
Nom de domaine HS

### ISSUE THREAD

**Issue by thom4parisot** [MattiSG/epicene.info#3]
Salut !

Le domaine epicene.info a l'air d'être HS, _et_ le site GitHub Pages redirige vers ce domaine.

Ça rend inaccessible le fichier `plist` [mentionné dans ce paragraphe][plist] de l'article Medium "Point médian final : point d’hyphénation" : 

```
https://mattisg.github.io/epicene.info/assets/ecriture-epicene.plist
```

As-tu prévu de le remettre en route ?\
Si non, est-ce possible de désactiver la redirection vers le domaine `epicene.info` ?

Ou toute autre solution dont la résolution rend à nouveau accessible cette ressource 🙂 

Merci d'avance

Thomas

[plist]: https://matti-sg-fr.medium.com/point-m%C3%A9dian-final-point-dhyph%C3%A9nation-3f749c32b659#da1c

**Comment by MattiSG** [comment]
Merci @thom4parisot pour le signalement !

J'ai effectivement laissé expiré ce nom de domaine pour lequel j'avais plus d'ambition que de faire simplement du stockage de fichiers, et pour lequel je n'ai rien fait en plusieurs années. J'avais oublié cette redirection. Après une rapide investigation, je crois qu'il faut mener les opérations suivantes (notes pour moi-même) :

- [x] Supprimer le fichier `CNAME`.
- [x] Modifier l'entrée `url` dans le fichier `_config.yml`.
- [x] Modifier les liens dans l'article Medium.
- [x] Modifier la configuration de GitHub Pages.
- [x] Ajouter la gestion de `baseurl` maintenant qu'on sert depuis un dossier et non plus sur `/`.

Je ne sais pas s'il y a beaucoup de backlinks vers `epicene.info` directement, ceux-là sont cassés aussi.

Une alternative consisterait à racheter le nom de domaine et configurer à nouveau ses DNS pour pointer vers les serveurs GitHub Pages. Ça peut m'être moins coûteux que le temps pour effectuer ces changements au final 😅

**Comment by MattiSG** [comment]
> racheter le nom de domaine

En période de rédemption, c'est bien trop cher.

**Comment by MattiSG** [comment]
Les liens sont a priori à nouveau tous fonctionnels sur l'article d'après deadlinkchecker.com

>

**Comment by MattiSG** [comment]
Les liens internes sont cassés. J'ai normalement corrigé via https://github.com/MattiSG/epicene.info/commit/63d44c4dfb155793353400d685949dcc4bc0c459, mais GitHub Pages ne déploie pas depuis. J'espère que cela va finir par arriver.
Dans tous les cas, le problème identifié dans cette issue est a priori corrigé.

Merci @thom4parisot pour le signalement ! 🙂
